# Generated by Django 4.1.2 on 2023-03-21 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='folder_id',
            new_name='folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='description',
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
