# Generated by Django 4.1.2 on 2023-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_folder_id_task_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
